Before you turn this problem in, make sure everything runs as expected. First, **restart the kernel** (in the menubar, select Kernel $\rightarrow$ Restart) and then **run all cells** (in the menubar, select Cell $\rightarrow$ Run All).

Make sure you fill in any place that says `YOUR CODE HERE` or "YOUR ANSWER HERE", as well as your name and collaborators below:

In [1]:
NAME = "Sümeyye Acar"
COLLABORATORS = ""

---

## Foundations of Data Literacy and Data Science
# Homework 4: The Numpy library

1) a) Create an array of zeros. It should have one row per student you remember sitting on your left in the last lecture, and one column in total. Among these students, insert a 1 for each woman you remember into a cell in this array. Also create an array of ones with the same shape (1 column, x rows). Then stack these two horizontally and call the resulting array *left*.

In [ ]:
import numpy as np

# M M M W W __ME__ M M

left_zeros = np.zeros((5, 1))

left_zeros[0, 0] = 1
left_zeros[1, 0] = 1

left_ones = np.ones((5, 1))

left = np.hstack((left_zeros, left_ones))
# raise NotImplementedError()

In [3]:
print(left)

[[1. 1.]
 [1. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]]


1) b) Do the same for the students you remember sitting on your right and call the resulting array *right*.

In [4]:
right_zeros = np.zeros((2, 1))

right_ones = np.ones((2, 1))

right = np.hstack((right_zeros, right_ones))
# raise NotImplementedError()

In [5]:
print(right)

[[0. 1.]
 [0. 1.]]


1) c) Compute the sums of the columns of both *left* and *right* and save the resulting arrays as *leftsum* and *rightsum*.

In [6]:
leftsum = np.sum(left, axis=0)
rightsum = np.sum(right, axis=0)

# raise NotImplementedError()

In [7]:
print(leftsum, rightsum)

[2. 5.] [0. 2.]


1) d) Add *leftsum* and *rightsum* together and save the result as *totalsum*. Then divide the first cell by the second cell and save the result as *womensquota*. Check that the quota is <= 1.

In [8]:
totalsum = leftsum + rightsum

womensquota = totalsum[0] / totalsum[1]

assert womensquota <= 1, "Quota exceeds 1"
# raise NotImplementedError()

In [9]:
print(womensquota)

0.2857142857142857


2) a) Create a column of zeros with the same number of rows as *left*. Stack it together horizontally with *left* (with *left* first and the new column second), calling the resulting array *left* again. 

In [10]:
new_column = np.zeros((left.shape[0], 1))

left = np.hstack((left, new_column))

# raise NotImplementedError()

In [11]:
print(left)

[[1. 1. 0.]
 [1. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]


2) b) Create a column of **ones** with the same number of rows as *right*. Stack it together horizontally with *right* (with *right* first and the new column second), calling the resulting array *right* again. 

In [12]:
new_column2 = np.ones((right.shape[0], 1))

right = np.hstack((right, new_column2))

# raise NotImplementedError()

In [13]:
print(right)

[[0. 1. 1.]
 [0. 1. 1.]]


2) c) Define a function *quotas* which takes two arrays like *left* and *right*, and returns both the total women's quota and the quota of people sitting on the left. It only needs to work on arrays such as we have created here. Use it on your *left* and *right* arrays and save the output in a variable called *results*.

In [14]:
def quotas(left, right):
    leftsum = np.sum(left, axis=0)
    rigthsum = np.sum(right, axis=0)

    # total women's quota
    totalsum = leftsum + rigthsum
    womensquota = totalsum[0] / totalsum[1]
    
    # the quota of people sitting on the left
    total_people = leftsum[1] + rightsum[1]
    leftquota = leftsum[1] / total_people
    
    return womensquota, leftquota

results = quotas(left, right)

# raise NotImplementedError()

In [15]:
print(results)

(np.float64(0.2857142857142857), np.float64(0.7142857142857143))


2) d) Get the unique values in *results*, calling the result *uni*.

In [16]:
uni = np.unique(results)

# raise NotImplementedError()

In [17]:
print(uni)

[0.28571429 0.71428571]


2) e) Save *results* into a csv file called "quotas.csv", with semicolons as delimiters.

In [18]:
np.savetxt("quotas.csv", results, delimiter=";",fmt="%s")
# raise NotImplementedError()